# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project_1'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  my_new_project_1:

    staging:  # ← Fixed: 4 spaces (not 6)
      +enabled: true
      #+schema: SOURCE
      +schema: staging_northwind
      +materialized: view

    warehouse:  # ← Fixed: 4 spaces (not 6)
      +enabled: true
      +materialized: table
      +schema: dwh_northwind
      dim_date:
        +materialized: view # this makes sure to make only the dim_date table a view in the warehouse folder

    analytics_obt:  # ← Fixed: 4 spaces (not 6)
      +enabled: true
      +materialized: table
      +schema: obt_northwind
